### ISSUE TITLE
Trying to use on kaggle, but get error when downloading.

### ISSUE THREAD

**Issue by ChrisRichardMiles** [robjhyndman/M4metalearning#17]
I put this into a kaggle r notebook: 
`devtools::install_github("robjhyndman/M4metalearning")`
But i get this error. 
![Screenshot (214)](https://user-images.githubusercontent.com/22208353/81015889-4ff27000-8e14-11ea-8e76-cc827a15dc4b.png)
It seems like the problem is with rlang, so maybe I should be posting there. I know nothing of R, but
I would really like to try your package on kaggle to predict time series. Thanks for all your contributions to the field of forecasting.

**Comment by robjhyndman** [comment]
Yes, this has nothing to do with M4metalearning. It is about the installation of other required packages.
