### ISSUE TITLE
Doubt about OWA and OWI erros

### ISSUE THREAD

**Issue by Joelmamarques** [robjhyndman/M4metalearning#18]
Good morning Dears,
In the FFORMA paper, the authors show the OWA (overall weighted average) as the Forecast loss measure. But, in the **'Forecasting Metalearning Example'** on GitHub, they use the OWI error to measure the performance. I just would like to know if the errors has the same meaning. They represent the same idea?

Thank you for your time.

**Comment by pmontman** [comment]
Thank you for your question, the OWA and OWI errors are the same "in spirit", OWI is a bugged version of OWA. OWI is normalizing SMAPE and MASE by the average error of the "Seasonal Naive" method. OWA error is normalizing by the "naive2" method introduced in the M4 competition.  There is no reason behind this difference, this was a mistake on our part.

**Comment by Joelmamarques** [comment]
Dear pmontman. Thank you so much for your time and explanation.
